main: 'me.kakalavala.jukebox.core.Core'
name: GlobalJukebox
version: 1.0
api-version: 1.13
description: Vote and play records to all players.
author: Kakalavala

commands:
  jukebox:
    description: Jukebox main command.
    aliases: [jb]